
owner: uptimereports
repo: iwebup
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36

workflowSchedule:
  uptime: "*/15 * * * *"
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"



delay: 2000

sites:
	
  - name: griffininsurance.net/new
    url: http://griffininsurance.net/new
    __dangerous__body_down_if_text_missing: "<footer data-elementor-type"
    



status-website:
  baseUrl: /iwebup
  name: Website Uptime Reports
  introTitle: "**Website Uptime & Integrity Monitoring**"
  introMessage: >
    Real-time monitoring for availability, footer integrity, and security issues.
    Powered by GitHub Actions and Upptime.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/uptimereports/iwebup

