
owner: uptimereports
repo: iwebup
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36

workflowSchedule:
  uptime: "*/15 * * * *"
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"



delay: 2000

sites:
  - name: 3guyslocksmiths.com
    url: https://3guyslocksmiths.com
    __dangerous__body_down_if_text_missing: "<footer"
    __dangerous__body_down: "Hacked by|Defaced|Account Suspended|This Account Has Been Suspended|Malware|Viagra|Cialis|Casino|Japanese Keyword Hack|Pharma hack|Pay ransom|Decryption key"
    
  - name: a1handymanfl.com
    url: https://a1handymanfl.com
    __dangerous__body_down_if_text_missing: "<footer data-elementor-type"
    __dangerous__body_down: "Hacked by|Defaced|Account Suspended|This Account Has Been Suspended|Malware|Viagra|Cialis|Casino|Japanese Keyword Hack|Pharma hack|Pay ransom|Decryption key"

status-website:
  # If you do NOT have a custom domain, keep cname commented out
  # cname: status.yourdomain.com

  baseUrl: /iwebup

  name: Website Uptime Reports
  introTitle: "**Website Uptime & Integrity Monitoring**"
  introMessage: >
    Real-time monitoring for availability, footer integrity, and security issues.
    Powered by GitHub Actions and Upptime.

  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/uptimereports/iwebup

    




